# Bootstrap Application - apply this to start the app-of-apps
# kubectl apply -f root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kinder-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/mattwillsher/kinder-argo.git
    path: apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
