{{- if .Values.certManagerIssuer.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-60"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.certManagerIssuer.namespace }}
  source:
    repoURL: {{ .Values.certManagerIssuer.repoURL }}
    targetRevision: {{ .Values.certManagerIssuer.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
